logging:
  config: classpath:log4j2.xml
server:
  port: 8080
  servlet:
    context-path: /xd

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:p6spy:mysql://159.226.16.168:26001/xiandao?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: xiandao
    password: qwer1234!@#$
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  thymeleaf:
    mode: HTML5
    encodeing: UTF-8
    cache: false
    servlet:
      content-typ: text/html
    prefix: classpath:/templates/

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false
   # super-mapper-class: org.crown.framework.mapper.BaseMapper
  #type-enums-package: org.crown.enums
  type-aliases-package: cn.cnic.xiandao.model
